mapReal = map( lambda x: np.real(x)*(1/4) , x )
    mapImag = map( lambda x: np.imag(x)*(1/4) , x )
    firstReal = islice( mapReal, 1 )
    firstImag = islice( mapImag, 1 )
    revReal = reversed( list(islice( mapReal , 1 , None )) )
    print( list(revReal) )
    revImag = reversed( list(islice( mapImag , 1 , None )) )
    compReal = chain( firstReal , revReal )
    compImag = chain( firstImag , revImag )
    complxList = map( np.complex , compReal , compImag )
    aa = list(complxList)
    return FFT(aa)
